### ISSUE TITLE
Dispose of hot-swapped apps

### ISSUE THREAD

**Issue by bengourley** [bengourley/choo-resume#2]
If at all possible (https://github.com/yoshuawuyts/barracks/issues/75) stop old versions of the app from running. Performance doesn't seem to be an issue _yet_ but I'm using `choo-log` and for each hot-swap of the app it multiplies the amount of logs per action.

**Comment by yoshuawuyts** [comment]
There's no way to close things through the choo API - not sure what an API
for this should look like / we should even add it. We could maybe extend
choo-log to be dismounted whenever we switch things out? Idk how tho

**Comment by bengourley** [comment]
Cool. I did wonder about a change to `choo-log` to do that sort of thing, however I'm going to revert on my statement

> Performance doesn't seem to be an issue yet

Once an app has been hot-swapped 10+ time it starts to feel noticeably laggy. I definitely thing this should happen at the state mgmt level.

**Comment by bengourley** [comment]
Update on this:

- `store.stop()` was added in https://github.com/yoshuawuyts/barracks/pull/76
- waiting on choo https://github.com/yoshuawuyts/choo/pull/359 to be merged before we can add the functionality here
